VOLUME{myVolume}=V1
NOTE{note}=C4
DURATION{duration}=T20
STREAM{stream}=(duration)+(note)+(myVolume)+(myVolume)
STREAM{stream2}=(stream)+C#4+22.32
NOTE{note2}=G#5
FREQUENCY{freq}=10.21
FUNCTION(myFunction)
NOTE{functionNote}=E8
ENDFUNCTION(myFunction)
CALL(myFunction)
STREAM{functionStream}=CALL(myFunction)+B2+T100
NOTE{note3}=E8
